source 'https://rubygems.org'
gem 'sinatra', '~> 2.0.0'
gem 'google_drive'
gem 'dotenv'
gem 'pry'
gem 'minitest'
gem 'mocha'
gem 'puma'
gem 'pdf-reader'
gem 'rake'
gem 'omniauth'
gem 'omniauth-google-oauth2'
